'use strict';

/**
 * Shared project data for projects.html (listing) and project.html (detail template).
 * Real projects only — no filler/placeholder entries.
 */
window.PROJECTS_DATA = [
  {
    slug: 'comic-explain',
    num: '01',
    title: 'Comic Explain',
    kind: 'personal',
    year: '2026',
    platforms: ['Web', 'iOS'],
    prize: '',
    meta: 'Studio · iPad + Web',
    href: 'https://www.comicexplain.com',
    img: 'public/assets/images/illustrations/comic-explain.svg',
    caption: 'technical concepts → educational manga',
    line: 'A prototyping studio for educational manga explainers. Paste prose, get a comic prompt bundle; companion app in SwiftUI.',
    description: 'A client-side prototyping studio for educational manga explainers. Paste prose, get a whole-comic prompt bundle; author per-page prompts, preview live, copy out to any image model. Ingests arXiv and PubMed papers from event links through an SSRF-guarded server hop. Companion native app in SwiftUI.',
    tags: ['Vite', 'React', 'TypeScript', 'SwiftUI', 'Vercel functions', 'Google Sign-In'],
    links: [
      { label: 'comicexplain.com ↗', href: 'https://www.comicexplain.com' },
      { label: 'Source ↗', href: 'https://github.com/romyilano/comicexplain' }
    ],
    featured: true
  },
  {
    slug: 'poelove',
    num: '02',
    title: 'Poelove',
    kind: 'personal',
    year: '2026',
    platforms: ['Web', 'visionOS'],
    prize: 'Vibe Coding award',
    meta: 'Language learning · VR',
    href: 'https://www.poelove.com',
    img: 'public/assets/images/backgrounds/projects/poelove_hero.jpg',
    caption: 'Pushkin, Akhmatova, my ink drawings',
    line: 'Learn a language through its poetry. Pushkin and Akhmatova line by line, hand-drawn illustrations, select poems in VR.',
    description: 'Learn a language through its poetry instead of lesson plans. Read Pushkin and Akhmatova line by line with translations, vocabulary in context, and hand-drawn illustrations; select poems open in VR. Started with Russian; the pipeline is language-agnostic.',
    tags: ['Web', 'visionOS', 'WebXR', 'Hand-drawn art'],
    links: [
      { label: 'poelove.com ↗', href: 'https://www.poelove.com' }
    ],
    featured: true
  },
  {
    slug: 'surf-or-skate',
    num: '03',
    title: 'Surf or Skate',
    kind: 'hackathon',
    year: '2026',
    platforms: ['Web'],
    prize: 'Best demo',
    meta: 'AI Agent Native Hackathon @ Cloudflare · Aug 2026',
    href: 'https://agentnativesurfskate.vercel.app',
    img: 'public/assets/images/illustrations/surf-or-skate.svg',
    caption: '8 agents argue, one answer, ~1s',
    line: 'Eight agents argue surf, skate, or bike using traffic, weather, and location. One answer in about a second.',
    description: 'Built in two days at the Agent Native Builders Hackathon at Cloudflare HQ. Answers "surf, skate, or bike?" by sending the question to eight independent agents that argue it out and land on one answer in about a second. Animated fleet diorama, live agent-to-agent stream, self-serve API with no signup.',
    tags: ['Cloudflare', 'Cotal A2A', 'Vercel', 'Frozen event schema', 'XR diorama'],
    links: [
      { label: 'Live ↗', href: 'https://agentnativesurfskate.vercel.app' },
      { label: 'Source ↗', href: 'https://github.com/romyilano/agent_native_surf_skate' }
    ],
    featured: true
  },
  {
    slug: 'cuentame',
    num: '04',
    title: 'Cuéntame',
    kind: 'hackathon',
    year: '2026',
    platforms: ['Web'],
    prize: '',
    meta: 'Health AI hackathon · 2026',
    href: 'https://github.com/romyilano/cuentame',
    img: 'public/assets/images/illustrations/cuentame.svg',
    caption: '"tell me" — 3D pain map, bilingual',
    line: 'A bilingual health hand-off: show a doctor where it hurts on a 3D body map and carry your history across a language barrier.',
    description: 'A patient-controlled, source-linked bilingual health hand-off. Show a doctor where it hurts on a 3D body map and carry your history across a language barrier. Vision model reads health-app screenshots into structured facts with per-fact confidence; text model translates to Spanish. Synthetic fixtures only, no real PHI.',
    tags: ['Next.js', 'TypeScript', 'Qwen2.5-VL 72B', 'Gemma 3', 'Nebius', 'AWS'],
    links: [
      { label: 'Repo + demo video ↗', href: 'https://github.com/romyilano/cuentame' }
    ],
    featured: true
  },
  {
    slug: 'diorama-xr',
    num: '05',
    title: 'Diorama XR',
    kind: 'hackathon',
    year: '2026',
    platforms: ['visionOS', 'Web'],
    prize: 'Third place',
    meta: "Builder's Night Hacks · Founders, Inc. · Mar 2026",
    href: '',
    img: '',
    caption: 'one prompt → visionOS + WebXR',
    line: 'AI tooling for a cross-platform XR engine: RealityKit dioramas and A-Frame WebXR from one source.',
    description: 'AI tooling for a cross-platform XR engine: RealityKit dioramas and A-Frame WebXR from one source.',
    tags: ['RealityKit', 'WebXR', 'A-Frame'],
    links: [],
    featured: true
  },
  {
    slug: 'poiret-salon',
    num: '06',
    title: 'Poiret Salon',
    kind: 'hackathon',
    year: '2026',
    platforms: ['iOS'],
    prize: 'Game Skills AI award',
    meta: 'AI Skills Hackathon · AGI House · Mar 2026',
    href: '',
    img: '',
    caption: 'skills for creatives, WWI France',
    line: 'Skills for creatives in a historical WWI drama in France. MCP-based orchestration generating SpriteKit assets and scaffolding.',
    description: 'Skills for creatives in a historical WWI drama in France. MCP-based orchestration generating SpriteKit assets and scaffolding.',
    tags: ['SpriteKit', 'MCP', 'iOS'],
    links: [],
    featured: true
  },
  {
    slug: 'california-legislative',
    num: '07',
    title: 'California Legislative',
    kind: 'hackathon',
    year: '2023',
    platforms: ['Web'],
    prize: 'Most insightful',
    meta: 'Stanford AI + Law Hackathon · 2023',
    href: '',
    img: '',
    caption: 'Llama 2 reads the legislature',
    line: 'Team project applying Llama 2 to California legislative text.',
    description: 'Team project applying Llama 2 to California legislative text.',
    tags: ['Llama 2'],
    links: [],
    featured: true
  },
  {
    slug: 'bento-rock',
    num: '08',
    title: 'Bento Rock',
    kind: 'personal',
    year: '2011',
    platforms: ['iOS'],
    prize: '',
    meta: 'Personal · iOS',
    href: '',
    img: '',
    caption: 'healthy eating, cartoon characters',
    line: 'Healthy-eating iOS app with cartoon characters, framed photos, drawing, and family sharing.',
    description: 'Healthy-eating iOS app with cartoon characters, framed photos, drawing, and family sharing.',
    tags: ['iOS'],
    links: [],
    featured: false
  },
  {
    slug: 'conference-360',
    num: '09',
    title: 'Conference 360',
    kind: 'personal',
    year: '2024',
    platforms: ['visionOS'],
    prize: '',
    meta: 'Personal · visionOS',
    href: '',
    img: '',
    caption: 'spatial conference viewer',
    line: 'Spatial conference viewer for Apple Vision Pro.',
    description: 'Spatial conference viewer for Apple Vision Pro.',
    tags: ['visionOS', 'RealityKit'],
    links: [],
    featured: false
  },
  {
    slug: 'model-mover',
    num: '10',
    title: 'Model Mover',
    kind: 'personal',
    year: '2024',
    platforms: ['visionOS'],
    prize: '',
    meta: 'Personal · visionOS',
    href: '',
    img: '',
    caption: 'place and move 3D models',
    line: 'Place and move 3D models in RealityKit.',
    description: 'Place and move 3D models in RealityKit.',
    tags: ['visionOS', 'RealityKit'],
    links: [],
    featured: false
  }
];
